### ISSUE TITLE
Actions fired multiple times

### ISSUE THREAD

**Issue by abdonrd** [PolymerLabs/polymer-redux-hn#17]
For example, if I click the reload button, the `REQUEST_LIST` action calls four times:

| From | To |
| ---- | -- |
| <img width="1552" alt="screen shot 2018-02-16 at 08 27 26" src="https://user-images.githubusercontent.com/1007051/36297525-8046cede-12f3-11e8-9e1a-58b3147f1d76.png"> | <img width="1552" alt="screen shot 2018-02-16 at 08 27 35" src="https://user-images.githubusercontent.com/1007051/36297526-81475286-12f3-11e8-87fd-318451c716f4.png"> |

And if I change from the Top tab to the New tab:
Two `REQUEST_LIST`, one `UPDATE_LOCATION` and two more `REQUEST_LIST`.

| From | To |
| ---- | -- |
| <img width="1552" alt="screen shot 2018-02-16 at 08 31 08" src="https://user-images.githubusercontent.com/1007051/36297596-ebeae4fe-12f3-11e8-9c8f-ddb5c3c1261b.png"> | <img width="1552" alt="screen shot 2018-02-16 at 08 31 38" src="https://user-images.githubusercontent.com/1007051/36297597-ecd673ba-12f3-11e8-9ad8-6bd2a8e6c114.png"> |

**Comment by keanulee** [comment]
That's `REQUEST_LIST` and `RECEIVE_LIST` (after the fetch completes), 2 different actions. `UPDATE_LOCATION` happens when you click a link.

**Comment by keanulee** [comment]
Also note there's an issue with the Redux devtools where actions don't appear after using `replaceReducer` (https://github.com/gaearon/redux-devtools/issues/378) - this is apparent in the "from" screenshots.

**Comment by abdonrd** [comment]
Wow! I don't understand how I read the same! 😱😳
Thanks and sorry @keanulee!
